# Generated by Django 6.0.6 on 2026-06-24 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vk_link', models.URLField(verbose_name='Ссылка ВКонтакте')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('work_type', models.CharField(choices=[('conspect', 'Конспект')], default='conspect', max_length=20)),
                ('pages', models.PositiveIntegerField(verbose_name='Объем работы (стр.)')),
                ('deadline', models.DateField(verbose_name='Срок сдачи')),
                ('paper_format', models.CharField(choices=[('A4_tetrad', 'Тетрадь А4'), ('A5_tetrad', 'Тетрадь А5'), ('A4_list', 'Лист А4')], max_length=20, verbose_name='Формат')),
                ('handwriting', models.CharField(choices=[('any', 'Не имеет значения'), ('readable', 'Разборчивый почерк'), ('individual', 'Индивидуальный подбор')], max_length=20, verbose_name='Почерк')),
                ('has_material', models.CharField(choices=[('yes', 'Есть готовый материал'), ('soon', 'Скоро появится')], max_length=5, verbose_name='Материал')),
                ('has_tables', models.BooleanField(default=False, verbose_name='Таблицы')),
                ('has_schemes', models.BooleanField(default=False, verbose_name='Схемы')),
                ('has_drawings', models.BooleanField(default=False, verbose_name='Рисунки')),
                ('text_only', models.BooleanField(default=False, verbose_name='Только текст')),
                ('additional_info', models.TextField(blank=True, verbose_name='Дополнительная информация')),
                ('get_type', models.CharField(choices=[('pickup', 'Заберу сам'), ('delivery', 'Нужна доставка')], max_length=20, verbose_name='Способ получения')),
                ('estimated_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ориентировочная цена')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('is_processed', models.BooleanField(default=False, verbose_name='Обработана')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
                'ordering': ['-created_at'],
            },
        ),
    ]
