# Generated by Django 6.0.6 on 2026-06-24 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='uploaded_file',
            field=models.FileField(blank=True, null=True, upload_to='orders/%Y/%m/', verbose_name='Файл с исходным материалом'),
        ),
    ]
