# Generated by Django 6.0.6 on 2026-06-27 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_uploaded_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='has_material',
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_address',
            field=models.CharField(default='', max_length=500, verbose_name='Адрес ПВЗ'),
        ),
        migrations.AddField(
            model_name='order',
            name='material_type',
            field=models.CharField(choices=[('document', 'Электронный документ'), ('presentation', 'Презентация'), ('handwritten_photo', 'Фото рукописного конспекта')], default='document', max_length=30, verbose_name='Тип материала'),
        ),
        migrations.AlterField(
            model_name='order',
            name='estimated_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Стоимость'),
        ),
        migrations.AlterField(
            model_name='order',
            name='get_type',
            field=models.CharField(default='delivery', max_length=20, verbose_name='Способ получения'),
        ),
        migrations.AlterField(
            model_name='order',
            name='handwriting',
            field=models.CharField(choices=[('any', 'Стандарт'), ('readable', 'Разборчивый'), ('individual', 'Индивидуальный подбор')], max_length=20, verbose_name='Почерк'),
        ),
        migrations.AlterField(
            model_name='order',
            name='paper_format',
            field=models.CharField(choices=[('A4_tetrad', 'Тетрадь А4'), ('A5_tetrad', 'Тетрадь А5')], max_length=20, verbose_name='Формат'),
        ),
        migrations.AlterField(
            model_name='order',
            name='uploaded_file',
            field=models.FileField(blank=True, null=True, upload_to='orders/%Y/%m/', verbose_name='Файл с материалом'),
        ),
    ]
