# Generated by Django 6.0.6 on 2026-06-27 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_remove_order_has_material_order_delivery_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_address',
            field=models.CharField(default='', max_length=500, verbose_name='Адрес ПВЗ Wildberries'),
        ),
    ]
